//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAKE
    {
        public int ID { get; set; }
        public string C_NAME { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string IMAGE_LINK { get; set; }
    
        public virtual TYPE_CAKE TYPE_CAKE { get; set; }
    }
}
