//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_DETAIL
    {
        public int SERIAL { get; set; }
        public int RECEIPT_ID { get; set; }
        public Nullable<int> CAKE_ID { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<int> TOTAL { get; set; }
    
        public virtual CAKE CAKE { get; set; }
        public virtual CAKE_TYPE CAKE_TYPE { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
    }
}
